name: Terraform Operations

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Select the environment for Terraform operations'
          required: true
          type: choice
          options:
            - "dev"
            - "qa"
            - "prod"
          default: "dev"
        action:
          description: 'Select the Terraform action to perform'
          required: true
          type: choice
          options:
            - "plan"
            - "apply"
            - "destroy"
          default: "plan"
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.environment }} - ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      ACTION: ${{ github.event.inputs.action }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.2
    
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-2
    
      - name: Terraform Initialization
        run: terraform init -backend-config=environments/${{ env.ENVIRONMENT }}/backend.hcl -reconfigure
    
      - name: Terraform plan
        if: env.ACTION == 'plan' || env.ACTION == 'apply'
        run: terraform plan -var-file=environments/${{ env.ENVIRONMENT}}/terraform.tfvars

      - name: Terraform apply
        id: apply
        if: env.ACTION == 'apply'
        run: terraform apply -var-file=environments/${{ env.ENVIRONMENT}}/terraform.tfvars -auto-approve

      - name: Terraform destroy
        if: env.ACTION == 'destroy' || steps.apply.outcome == 'failure'
        run: terraform destroy -var-file=environments/${{ env.ENVIRONMENT}}/terraform.tfvars -auto-approve